# Generated by Django 4.1.1 on 2022-09-17 14:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(validators=[django.core.validators.RegexValidator(message='Введите номер в формате "7**********"', regex='7[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')])),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('content', models.TextField()),
                ('end_time', models.DateTimeField()),
                ('codes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.codes')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.client')),
                ('mailingList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.mailinglist')),
            ],
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.tags'),
        ),
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.codes'),
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.tags'),
        ),
    ]
