# Generated by Django 4.1.1 on 2022-09-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglist',
            name='tags',
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='tags',
            field=models.ManyToManyField(to='sender.tags'),
        ),
    ]
