# Generated by Django 4.1.1 on 2022-09-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_remove_client_tags_client_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='code',
        ),
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.ManyToManyField(to='sender.codes'),
        ),
    ]
