# Generated by Django 4.1.1 on 2022-09-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_remove_client_code_client_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglist',
            name='codes',
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='codes',
            field=models.ManyToManyField(to='sender.codes'),
        ),
    ]
